---
- name: Install some needed packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
      - redis-server
      - git
      - curl
      - gnupg2
  when: ansible_os_family == "Debian"

- name: Enable EPEL repo
  yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"

- name: Install some needed packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - redis
      - git
      - curl
      - gnupg2
  when: ansible_os_family == "RedHat"

- include_tasks: apt.yml
  when:
    - ansible_os_family == "Debian"
    - use_repo

- include_tasks: git.yml
  when: use_repo == false

- include_tasks: rvm.yml
  when: use_repo == false

# not supported ATM
#
#- include: yum.yml
#  when:
#    - ansible_os_family == "RedHat"
#    - use_repo
