---

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Create mysql config file with credentials
  template:
    src: "templates/my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: Create the IDB database
  mysql_db:
   name: idb
   state: present
  tags:
    - mysql

- name: Create IDB MySQL user
  mysql_user:
   name: idb
   password: "{{ idb_mysql_password }}"
   priv: 'idb.*:ALL'
   state: present
  tags:
    - mysql

- name: Adjust MySQL user settings in IDB config
  lineinfile:
    dest: "/opt/the-idb/config/database.yml"
    regexp: "password"
    line: "  password: {{ idb_mysql_password }}"
    state: present
  tags:
    - mysql



...
